exclude: ".git/|.tox|dist|docs/source/_build|docs/html/|docs/doctrees/|((?:[^/]*/)*)(.svg)|((?:[^/]*/)*)(.xml)|rstcloth.egg-info"
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3

repos:
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
