from typing import Literal, overload

from src.const import JSONType, MeetupData, SpeakerData

@overload
def get_json_objects(type_: JSONType, *ids) -> list: ...
@overload
def get_json_objects(type_: Literal[JSONType.MEETUPS], *ids) -> list[MeetupData]: ...
@overload
def get_json_objects(type_: Literal[JSONType.SPEAKERS], *ids) -> list[SpeakerData]: ...
def get_meetups(*ids) -> list[MeetupData]: ...
def get_speakers(*ids) -> list[SpeakerData]: ...
