from typing import Any, List, Literal, overload

from src.const import JSONType, MeetupData, SpeakerData

@overload
def get_json_objects(type_: JSONType, *ids) -> List[Any]: ...
@overload
def get_json_objects(type_: Literal[JSONType.MEETUPS], *ids) -> List[MeetupData]: ...
@overload
def get_json_objects(type_: Literal[JSONType.SPEAKERS], *ids) -> List[SpeakerData]: ...
def get_meetups(*ids) -> List[MeetupData]: ...
def get_speakers(*ids) -> List[SpeakerData]: ...
